language: android	
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.0.1

    # The SDK version used to compile your project
    - android-21
    - sys-img-armeabi-v7a-android-21
  before_install:
    - chmod +x gradlew
  script: ./gradlew build assembleDebug